name: Obfuscate JS and Deploy to Firebase
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Get repository from repo server to runner
        uses: actions/checkout@v2
      - name: Obfuscate codes
        run: | 
          npm i -g javascript-obfuscator
          cp -r ./development/public ./production/
          javascript-obfuscator ./production/public/ --output ./production/public/
      - name: List development files
        run: |
          echo -e "Built on $(date)\n"      | tee ./production/build.list
          echo "Readable code sizes:"       | tee -a ./production/build.list
          du -ha ./development/public/      | grep "\.js" | tee -a ./production/build.list
          echo                              | tee -a ./production/build.list
      - name: List production files
        run: |
          echo "Obfuscated code sizes:"     | tee -a ./production/build.list
          du -ha ./production/public/       | grep "\.js" | tee -a ./production/build.list
          echo                              | tee -a ./production/build.list
      - name: Install Firebase tools
        run: |
          npm i -g firebase-tools
      - name: Firebase deploy
        run: |
          cd ./production
          firebase use sozialm --token "${{ secrets.FIREBASE_TOKEN }}"
          firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
