name: Obfuscate JS and Deploy to Firebase
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Get repository from repo server to runner
        uses: actions/checkout@v2
      - name: Obfuscate codes
        run: |
          echo -e "Built on $(date)\n"       | tee ./production/build.list
          echo "Readable code sizes:"        | tee -a ./production/build.list
          du -ha ./development/public/       | grep "\.js" | tee -a ./production/build.list
          echo                               | tee -a ./production/build.list
          npm i -g javascript-obfuscator
          cp -r ./development/public ./production/
          javascript-obfuscator ./production/public/ --output ./production/public/
      - name: Firebase deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: sozialnmedien
          PROJECT_PATH: ./production
      - name: List and delete production files
        run: |
            echo "Obfuscated code sizes:"     | tee -a ./production/build.list
            du -ha ./production/public/       | grep "\.js" | tee -a ./production/build.list
            echo                              | tee -a ./production/build.list
            rm -rf ./production/public/*
      - name: Git commit and push
        run: |
          echo "Git commit and push:"                              | tee -a ./production/build.list
          git config --global user.name "CinexSoft"
          git config --global user.email "cinexsoft@gmail.com"
          git add -A                                               | tee -a ./production/build.list
          git commit -m "Obfuscated JS and deployed to Firebase"   | tee -a ./production/build.list
          git push                                                 | tee -a ./production/build.list
