name: Obfuscate JS and Deploy to Firebase
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository from repo server to runner
        uses: actions/checkout@v2
      - name: Obfuscate codes
        run: |
          npm i -g javascript-obfuscator
          cp -r ./development/public ./production/
          javascript-obfuscator ./production/public/ --output ./production/public/
      - name: Firebase deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: sozialnmedien
          PROJECT_PATH: ./production
      - name: List and delete production files
        run: |
            du -ha ./production/public/ | grep ".js" | tee ./production/build.list
            rm -rf ./production/public/*
      - name: Git commit and push
        run: |
          git config --global user.name "CinexSoft"
          git config --global user.email "cinexsoft@gmail.com"
          git add -A
          git commit -m "Javascript codes obfuscated"
          git push
