name: Obfuscate JS and Deploy to Preview
on:
  push:
    branches:
      - '*'
      - '!main'
      - '!master'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Get repository from repo server to runner
        uses: actions/checkout@v2
      - name: Obfuscate codes
        run: |
          echo -e "Built on $(date)\n"       | tee ./production/preview.build.list
          echo "Readable code sizes:"        | tee -a ./production/preview.build.list
          du -ha ./development/public/       | grep "\.js" | tee -a ./production/preview.build.list
          echo                               | tee -a ./production/preview.build.list
          npm i -g javascript-obfuscator
          cp -r ./development/public ./production/
          javascript-obfuscator ./production/public/ --output ./production/public/
      - name: Install Firebase tools
        run: |
          npm i -g firebase-tools
          firebase login --interactive --token "${{ secrets.FIREBASE_TOKEN }}"
      - name: Deploy to preview
        run: |
          cd ./production
          firebase use sozialnmedien
          firebase hosting:channel:deploy -e 2d preview$(date | sed "s/\s//g" | sed "s/://g")
      - name: List preview channels
        run: |
          echo "Firebase channels"          | tee -a ./production/preview.build.list
          firebase hosting:channel:list     | tee -a ../production/preview.build.list
          echo
          cd ../
      - name: List and delete production files
        run: |
          echo "Obfuscated code sizes:"     | tee -a ./production/preview.build.list
          du -ha ./production/public/       | grep "\.js" | tee -a ./production/preview.build.list
          echo                              | tee -a ./production/preview.build.list
          rm -rf ./production/public/*
      - name: Git commit and push
        run: |
          git config --global user.name "CinexSoft"
          git config --global user.email "cinexsoft@gmail.com"
          git add -A                                               | tee -a ./production/preview.build.list
          git commit -m "Obfuscated JS and deployed to Preview"    | tee -a ./production/preview.build.list
          git push                                                 | tee -a ./production/preview.build.list
